# Generated by Django 5.1.6 on 2025-02-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=255, verbose_name='Nome do evento'),
        ),
    ]
